
cfg = dict(
    model_type='bisenetv1_repvit_m3',
    n_cats=9,
    num_aux_heads=2,
    lr_start=0.0004,
    weight_decay=2e-4,
    warmup_iters=2500,
    max_iter=86,
    max_epochs=300,
    dataset='BlueFaceDataset',
    im_root='../../BlueFaceDataX',
    train_im_anns='../../BlueFaceDataX/train.txt',
    val_im_anns='../../BlueFaceDataX/val.txt',
    scales=[0.5, 1.5],
    cropsize=[512, 512],
    eval_crop=[512, 512],
    eval_scales=[0.5, 0.75, 1, 1.25, 1.5, 1.75],
    ims_per_gpu=40,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)
