
cfg = dict(
    model_type='bisenetv1_convnext_small_transpose_sep_atrous_aux4',
    n_cats=9,
    num_aux_heads=4,
    lr_start=0.0006,
    weight_decay=5e-4,
    warmup_iters=2500,
    max_iter=50,
    max_epochs=800,
    dataset='BlueFaceDataset',
    im_root='../../BlueFaceDataV5',
    train_im_anns='../../BlueFaceDataV5/train.txt',
    val_im_anns='../../BlueFaceDataV5/val.txt',
    scales=[0.75, 1.25],
    cropsize=[512, 512],
    eval_crop=[512, 512],
    eval_scales=[0.5, 0.75, 1, 1.25, 1.5, 1.75],
    ims_per_gpu=25,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)
