
cfg = dict(
    model_type='bisenetv1_efficientnet_b3_slim',
    n_cats=9,
    num_aux_heads=2,
    lr_start=0.0002,
    weight_decay=1e-4,
    max_epochs=400,
    dataset='BlueFaceDataset',
    im_root='../../BlueFaceDataVX33',
    train_im_anns='../../BlueFaceDataVX33/train.txt',
    val_im_anns='../../BlueFaceDataVX33/val.txt',
    scales=[0.75, 2.0],
    cropsize=[512, 512],
    ims_per_gpu=32,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)
