
cfg = dict(
    model_type='bisenetv1_efficientnet_b3_pruned',
    n_cats=9,
    num_aux_heads=2,
    lr_start=0.0003,
    weight_decay=5e-4,
    warmup_iters=2500,
    max_iter=342,
    max_epochs=300,
    dataset='BlueFaceDataset',
    im_root='../../BlueFaceDataX',
    train_im_anns='../../BlueFaceDataX/train.txt',
    val_im_anns='../../BlueFaceDataX/val.txt',
    scales=[0.5, 1.5],
    cropsize=[512, 512],
    ims_per_gpu=20,
    eval_ims_per_gpu=1,
    use_fp16=False,
    use_sync_bn=False,
    respth='./res',
)
